src/Entity/Availability.php
<?php

namespace App\Entity;

use App\Repository\AvailabilityRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AvailabilityRepository::class)]
class Availability
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $consultation_duration = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $mon_start_hour = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $mon_end_hour = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $tue_start_hour = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $tue_end_hour = null;


    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $wed_end_hour = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $thu_start_hour = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $thu_end_hour = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $sat_start_hour = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $sat_end_hour = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fri_start_hour = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fri_end_hour = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $sun_start_hour = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $sun_end_hour = null;

    #[ORM\OneToOne(inversedBy: 'availability', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Doctor $doctor = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $wed_start_hour = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getConsultationDuration(): ?int
    {
        return $this->consultation_duration;
    }

    public function setConsultationDuration(int $consultation_duration): static
    {
        $this->consultation_duration = $consultation_duration;

        return $this;
    }

    public function getMonStartHour(): ?\DateTimeInterface
    {
        return $this->mon_start_hour;
    }

    public function setMonStartHour(\DateTimeInterface $mon_start_hour): static
    {
        $this->mon_start_hour = $mon_start_hour;

        return $this;
    }

    public function getMonEndHour(): ?\DateTimeInterface
    {
        return $this->mon_end_hour;
    }

    public function setMonEndHour(?\DateTimeInterface $mon_end_hour): static
    {
        $this->mon_end_hour = $mon_end_hour;

        return $this;
    }

    public function getTueStartHour(): ?\DateTimeInterface
    {
        return $this->tue_start_hour;
    }

    public function setTueStartHour(?\DateTimeInterface $tue_start_hour): static
    {
        $this->tue_start_hour = $tue_start_hour;

        return $this;
    }

    public function getTueEndHour(): ?\DateTimeInterface
    {
        return $this->tue_end_hour;
    }

    public function setTueEndHour(?\DateTimeInterface $tue_end_hour): static
    {
        $this->tue_end_hour = $tue_end_hour;

        return $this;
    }


    public function getWedEndHour(): ?\DateTimeInterface
    {
        return $this->wed_end_hour;
    }

    public function setWedEndHour(?\DateTimeInterface $wed_end_hour): static
    {
        $this->wed_end_hour = $wed_end_hour;

        return $this;
    }

    public function getThuStartHour(): ?\DateTimeInterface
    {
        return $this->thu_start_hour;
    }

    public function setThuStartHour(?\DateTimeInterface $thu_start_hour): static
    {
        $this->thu_start_hour = $thu_start_hour;

        return $this;
    }

    public function getThuEndHour(): ?\DateTimeInterface
    {
        return $this->thu_end_hour;
    }

    public function setThuEndHour(?\DateTimeInterface $thu_end_hour): static
    {
        $this->thu_end_hour = $thu_end_hour;

        return $this;
    }

    public function getSatStartHour(): ?\DateTimeInterface
    {
        return $this->sat_start_hour;
    }

    public function setSatStartHour(?\DateTimeInterface $sat_start_hour): static
    {
        $this->sat_start_hour = $sat_start_hour;

        return $this;
    }

    public function getSatEndHour(): ?\DateTimeInterface
    {
        return $this->sat_end_hour;
    }

    public function setSatEndHour(?\DateTimeInterface $sat_end_hour): static
    {
        $this->sat_end_hour = $sat_end_hour;

        return $this;
    }

    public function getFriStartHour(): ?\DateTimeInterface
    {
        return $this->fri_start_hour;
    }

    public function setFriStartHour(?\DateTimeInterface $fri_start_hour): static
    {
        $this->fri_start_hour = $fri_start_hour;

        return $this;
    }

    public function getFriEndHour(): ?\DateTimeInterface
    {
        return $this->fri_end_hour;
    }

    public function setFriEndHour(?\DateTimeInterface $fri_end_hour): static
    {
        $this->fri_end_hour = $fri_end_hour;

        return $this;
    }

    public function getSunStartHour(): ?\DateTimeInterface
    {
        return $this->sun_start_hour;
    }

    public function setSunStartHour(?\DateTimeInterface $sun_start_hour): static
    {
        $this->sun_start_hour = $sun_start_hour;

        return $this;
    }

    public function getSunEndHour(): ?\DateTimeInterface
    {
        return $this->sun_end_hour;
    }

    public function setSunEndHour(?\DateTimeInterface $sun_end_hour): static
    {
        $this->sun_end_hour = $sun_end_hour;

        return $this;
    }

    public function getDoctor(): ?Doctor
    {
        return $this->doctor;
    }

    public function setDoctor(Doctor $doctor): static
    {
        $this->doctor = $doctor;

        return $this;
    }

    public function getWedStartHour(): ?\DateTimeInterface
    {
        return $this->wed_start_hour;
    }

    public function setWedStartHour(?\DateTimeInterface $wed_start_hour): static
    {
        $this->wed_start_hour = $wed_start_hour;

        return $this;
    }
}

src/Form/AvailabilityType.php
<?php

namespace App\Form;

use App\Entity\Availability;
use App\Entity\Doctor;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AvailabilityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('consultation_duration')
            ->add('mon_start_hour')
            ->add('mon_end_hour')
            ->add('tue_start_hour')
            ->add('tue_end_hour')
            ->add('wed_start_hour')
            ->add('wed_end_hour')
            ->add('thu_start_hour')
            ->add('thu_end_hour')
            ->add('sat_start_hour')
            ->add('sat_end_hour')
            ->add('fri_start_hour')
            ->add('fri_end_hour')
            ->add('sun_start_hour')
            ->add('sun_end_hour')
            ->add('doctor', EntityType::class, [
                'class' => Doctor::class,
'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Availability::class,
        ]);
    }
}

src/Controller/AvailabilityController.php
<?php

namespace App\Controller;

use App\Entity\Availability;
use App\Form\AvailabilityType;
use App\Repository\AvailabilityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/availability')]
class AvailabilityController extends AbstractController
{
    #[Route('/', name: 'app_availability_index', methods: ['GET'])]
    public function index(AvailabilityRepository $availabilityRepository): Response
    {
        return $this->render('availability/index.html.twig', [
            'availabilities' => $availabilityRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_availability_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $availability = new Availability();
        $form = $this->createForm(AvailabilityType::class, $availability);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($availability);
            $entityManager->flush();

            return $this->redirectToRoute('app_availability_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('availability/new.html.twig', [
            'availability' => $availability,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_availability_show', methods: ['GET'])]
    public function show(Availability $availability): Response
    {
        return $this->render('availability/show.html.twig', [
            'availability' => $availability,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_availability_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Availability $availability, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AvailabilityType::class, $availability);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_availability_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('availability/edit.html.twig', [
            'availability' => $availability,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_availability_delete', methods: ['POST'])]
    public function delete(Request $request, Availability $availability, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$availability->getId(), $request->request->get('_token'))) {
            $entityManager->remove($availability);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_availability_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/availability/_delete_form.html.twig
<form method="post" action="{{ path('app_availability_delete', {'id': availability.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ availability.id) }}">
    <button class="btn">Delete</button>
</form>

templates/availability/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/availability/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Availability{% endblock %}

{% block body %}
    <h1>Edit Availability</h1>

    {{ include('availability/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_availability_index') }}">back to list</a>

    {{ include('availability/_delete_form.html.twig') }}
{% endblock %}

templates/availability/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Availability index{% endblock %}

{% block body %}
    <h1>Availability index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Consultation_duration</th>
                <th>Mon_start_hour</th>
                <th>Mon_end_hour</th>
                <th>Tue_start_hour</th>
                <th>Tue_end_hour</th>
                <th>Wed_start_hour</th>
                <th>Wed_end_hour</th>
                <th>Thu_start_hour</th>
                <th>Thu_end_hour</th>
                <th>Sat_start_hour</th>
                <th>Sat_end_hour</th>
                <th>Fri_start_hour</th>
                <th>Fri_end_hour</th>
                <th>Sun_start_hour</th>
                <th>Sun_end_hour</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for availability in availabilities %}
            <tr>
                <td>{{ availability.id }}</td>
                <td>{{ availability.consultationDuration }}</td>
                <td>{{ availability.monStartHour ? availability.monStartHour|date('H:i:s') : '' }}</td>
                <td>{{ availability.monEndHour ? availability.monEndHour|date('H:i:s') : '' }}</td>
                <td>{{ availability.tueStartHour ? availability.tueStartHour|date('H:i:s') : '' }}</td>
                <td>{{ availability.tueEndHour ? availability.tueEndHour|date('H:i:s') : '' }}</td>
                <td>{{ availability.wedStartHour ? availability.wedStartHour|date('H:i:s') : '' }}</td>
                <td>{{ availability.wedEndHour ? availability.wedEndHour|date('H:i:s') : '' }}</td>
                <td>{{ availability.thuStartHour ? availability.thuStartHour|date('H:i:s') : '' }}</td>
                <td>{{ availability.thuEndHour ? availability.thuEndHour|date('H:i:s') : '' }}</td>
                <td>{{ availability.satStartHour ? availability.satStartHour|date('H:i:s') : '' }}</td>
                <td>{{ availability.satEndHour ? availability.satEndHour|date('H:i:s') : '' }}</td>
                <td>{{ availability.friStartHour ? availability.friStartHour|date('H:i:s') : '' }}</td>
                <td>{{ availability.friEndHour ? availability.friEndHour|date('H:i:s') : '' }}</td>
                <td>{{ availability.sunStartHour ? availability.sunStartHour|date('H:i:s') : '' }}</td>
                <td>{{ availability.sunEndHour ? availability.sunEndHour|date('H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_availability_show', {'id': availability.id}) }}">show</a>
                    <a href="{{ path('app_availability_edit', {'id': availability.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="17">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_availability_new') }}">Create new</a>
{% endblock %}

templates/availability/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Availability{% endblock %}

{% block body %}
    <h1>Create new Availability</h1>

    {{ include('availability/_form.html.twig') }}

    <a href="{{ path('app_availability_index') }}">back to list</a>
{% endblock %}

templates/availability/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Availability{% endblock %}

{% block body %}
    <h1>Availability</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ availability.id }}</td>
            </tr>
            <tr>
                <th>Consultation_duration</th>
                <td>{{ availability.consultationDuration }}</td>
            </tr>
            <tr>
                <th>Mon_start_hour</th>
                <td>{{ availability.monStartHour ? availability.monStartHour|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Mon_end_hour</th>
                <td>{{ availability.monEndHour ? availability.monEndHour|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Tue_start_hour</th>
                <td>{{ availability.tueStartHour ? availability.tueStartHour|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Tue_end_hour</th>
                <td>{{ availability.tueEndHour ? availability.tueEndHour|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Wed_start_hour</th>
                <td>{{ availability.wedStartHour ? availability.wedStartHour|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Wed_end_hour</th>
                <td>{{ availability.wedEndHour ? availability.wedEndHour|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Thu_start_hour</th>
                <td>{{ availability.thuStartHour ? availability.thuStartHour|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Thu_end_hour</th>
                <td>{{ availability.thuEndHour ? availability.thuEndHour|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Sat_start_hour</th>
                <td>{{ availability.satStartHour ? availability.satStartHour|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Sat_end_hour</th>
                <td>{{ availability.satEndHour ? availability.satEndHour|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Fri_start_hour</th>
                <td>{{ availability.friStartHour ? availability.friStartHour|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Fri_end_hour</th>
                <td>{{ availability.friEndHour ? availability.friEndHour|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Sun_start_hour</th>
                <td>{{ availability.sunStartHour ? availability.sunStartHour|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Sun_end_hour</th>
                <td>{{ availability.sunEndHour ? availability.sunEndHour|date('H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_availability_index') }}">back to list</a>

    <a href="{{ path('app_availability_edit', {'id': availability.id}) }}">edit</a>

    {{ include('availability/_delete_form.html.twig') }}
{% endblock %}